createTime: '2022-04-06T12:31:25.455592839Z'
filename: build/03-with-cloud-deploy.yaml
id: 999d9c11-ee58-4fc9-af8f-69347b273377
name: advanced-cicd-build
substitutions:
  _ARTIFACT_REGISTRY_REPO: simple-cicd-demo
  _COMPUTE_CLUSTER: k8s
  _COMPUTE_ZONE: europe-west1-b
  _GCP_PROJECT: aflalo-cicd-demo
  _GCP_REGION: europe-west1
  _IMAGE_NAME: demo-app
  _DEPLOY_PIPELINE: run-pipeline
  _SEVERITY: critical
triggerTemplate:
  branchName: ^main$
  projectId: aflalo-cicd-demo
  repoName: aflalo-cicd-demo
